# Generated by Django 3.1.2 on 2020-10-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historialesmedicos',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pacientes.pacientes')),
                ('idpaciente', models.IntegerField()),
                ('enfermedadescronicas', models.CharField(max_length=100)),
                ('numcirugias', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('fechanacimiento', models.DateTimeField()),
            ],
            options={
                'db_table': 'historialesmedicos',
                'managed': False,
            },
        ),
    ]
