# Generated by Django 3.1.2 on 2020-10-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruposfamiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregrupo', models.CharField(db_column='nombreGrupo', max_length=100)),
            ],
            options={
                'db_table': 'gruposfamiliares',
                'managed': False,
            },
        ),
    ]
