# Generated by Django 3.1.2 on 2020-10-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numdocumento', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('tarjetaprofecional', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medicos',
                'managed': False,
            },
        ),
    ]
