# Generated by Django 3.1.2 on 2020-10-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examenesmedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomexamen', models.CharField(db_column='nomExamen', max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'examenesmedicos',
                'managed': False,
            },
        ),
    ]
